/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bE9NMB942w5e6uFrcCxfJN
// Component: qxSFoB0gpuxc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import AuthProvider from "../../AuthProvider"; // plasmic-import: KTPu1eZupEdG/component
import Layout from "../../Layout"; // plasmic-import: ve2FygUyzJYe/component
import Paziresh24Modal from "../../Paziresh24Modal"; // plasmic-import: ZGdhyEBPJSmH/component
import Paziresh24Button from "../../Paziresh24Button"; // plasmic-import: YOhw5fIQJQgB/component
import { Input } from "@/fragment/components/input"; // plasmic-import: AWE69UKwmIyg/codeComponent
import { AntdCheckbox } from "@plasmicpkgs/antd5/skinny/registerCheckbox";
import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: WP6AANBbVJxr/codeComponent
import WebhookCard from "../../WebhookCard"; // plasmic-import: OpfjC8Ncgqxa/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectcss
import sty from "./PlasmicWebhooks.module.css"; // plasmic-import: qxSFoB0gpuxc/css

import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: UuDHOUXMn1lI/icon
import ChevronLeftIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: jS0YlkKPLO7U/icon
import ChevronRightIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronRight"; // plasmic-import: 0359howWu0cr/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: rQsx35tf_bcf/icon

createPlasmicElementProxy;

export type PlasmicWebhooks__VariantMembers = {};
export type PlasmicWebhooks__VariantsArgs = {};
type VariantPropType = keyof PlasmicWebhooks__VariantsArgs;
export const PlasmicWebhooks__VariantProps = new Array<VariantPropType>();

export type PlasmicWebhooks__ArgsType = {};
type ArgPropType = keyof PlasmicWebhooks__ArgsType;
export const PlasmicWebhooks__ArgProps = new Array<ArgPropType>();

export type PlasmicWebhooks__OverridesType = {
  root?: Flex__<"div">;
  embedHtml?: Flex__<typeof Embed>;
  authProvider?: Flex__<typeof AuthProvider>;
  layout?: Flex__<typeof Layout>;
  dialog?: Flex__<typeof Paziresh24Modal>;
  input?: Flex__<typeof Input>;
  subscriptionCheck?: Flex__<typeof AntdCheckbox>;
  apiRequest?: Flex__<typeof ApiRequest>;
  webhookCard?: Flex__<typeof WebhookCard>;
};

export interface DefaultWebhooksProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWebhooks__RenderFunc(props: {
  variants: PlasmicWebhooks__VariantsArgs;
  args: PlasmicWebhooks__ArgsType;
  overrides: PlasmicWebhooks__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "authProvider.user",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "authProvider.apps",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "dialog.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "authProvider.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "authProvider.error",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "subscriptionCheck.checked",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicWebhooks.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicWebhooks.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicWebhooks.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
          dir={"rtl"}
        >
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<link\r\n  rel="stylesheet"\r\n  href="https://hamdast.paziresh24.com/static/player/style.css"\r\n/>\r\n<script src="https://hamdast.paziresh24.com/static/player/index.js"></script>'
            }
          />

          <AuthProvider
            data-plasmic-name={"authProvider"}
            data-plasmic-override={overrides.authProvider}
            className={classNames("__wab_instance", sty.authProvider)}
            onAppsChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["authProvider", "apps"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onErrorChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "authProvider",
                "error"
              ]).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onLoadingChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, [
                "authProvider",
                "loading"
              ]).apply(null, eventArgs);

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onUserChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["authProvider", "user"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
          >
            <Layout
              data-plasmic-name={"layout"}
              data-plasmic-override={overrides.layout}
              apps={(() => {
                try {
                  return $state.authProvider.apps;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              className={classNames("__wab_instance", sty.layout)}
              selectedApp={(() => {
                try {
                  return $ctx.params.id;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              selectedMenu={(() => {
                try {
                  return (
                    $ctx.pageRoute
                      .split("/")
                      [$ctx.pageRoute.split("/")?.length - 1][0].toUpperCase() +
                    $ctx.pageRoute
                      .split("/")
                      [$ctx.pageRoute.split("/")?.length - 1].slice(1)
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              showAppSidebar={true}
              user={(() => {
                try {
                  return $state.authProvider.user;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            >
              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__y6ZRp,
                  "no-scroll"
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__yl6Lw)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hDxhN)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mddF
                      )}
                    >
                      {"\u0648\u0628\u200c\u0647\u0648\u06a9 \u0647\u0627"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__idHmm
                      )}
                    >
                      {
                        "\u06af\u0648\u0634 \u062f\u0627\u062f\u0646 \u0628\u0647 \u0631\u0648\u06cc\u062f\u0627\u062f\u0647\u0627\u06cc \u0627\u0628\u0632\u0627\u0631\u06a9"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___74DQw)}
                  >
                    <Paziresh24Modal
                      data-plasmic-name={"dialog"}
                      data-plasmic-override={overrides.dialog}
                      body={
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yza1F
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jn7ZX
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__u8I4F
                              )}
                            >
                              {
                                "\u0622\u062f\u0631\u0633 \u0648\u0628\u200c\u0647\u0648\u06a9"
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zE9T
                              )}
                            >
                              {
                                "\u0645\u0627 \u06cc\u06a9 \u062f\u0631\u062e\u0648\u0627\u0633\u062a POST \u0628\u0647 \u0647\u0645\u0631\u0627\u0647 \u062c\u0632\u0626\u06cc\u0627\u062a \u0647\u0631 \u0631\u0648\u06cc\u062f\u0627\u062f \u0628\u0647 URL \u0632\u06cc\u0631 \u0627\u0631\u0633\u0627\u0644 \u062e\u0648\u0627\u0647\u06cc\u0645 \u06a9\u0631\u062f.\r"
                              }
                            </div>
                            <Input
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              attributes={{ dir: "ltr" }}
                              className={classNames(
                                "__wab_instance",
                                sty.input
                              )}
                              onChange={async (...eventArgs: any) => {
                                generateStateOnChangeProp($state, [
                                  "input",
                                  "value"
                                ]).apply(null, eventArgs);
                              }}
                              placeholder={"https://example.com/postreceive"}
                              type={"text"}
                              value={generateStateValueProp($state, [
                                "input",
                                "value"
                              ])}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ozFbZ
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lpui7
                              )}
                            >
                              {"\u0631\u0648\u06cc\u062f\u0627\u062f"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dmTDp
                              )}
                            >
                              {
                                "\u0686\u0647 \u0646\u0648\u0639 \u0631\u0648\u06cc\u062f\u0627\u062f \u0647\u0627\u06cc\u06cc \u0628\u0647 \u0627\u0628\u0632\u0627\u0631\u06a9 \u0627\u0637\u0644\u0627\u0639\u200c\u0631\u0633\u0627\u0646\u06cc \u0634\u0648\u062f\u061f"
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sTEt
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__pt5Aw
                                )}
                              >
                                <AntdCheckbox
                                  data-plasmic-name={"subscriptionCheck"}
                                  data-plasmic-override={
                                    overrides.subscriptionCheck
                                  }
                                  checked={generateStateValueProp($state, [
                                    "subscriptionCheck",
                                    "checked"
                                  ])}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.subscriptionCheck
                                  )}
                                  indeterminate={false}
                                  onChange={async (...eventArgs: any) => {
                                    generateStateOnChangeProp($state, [
                                      "subscriptionCheck",
                                      "checked"
                                    ]).apply(null, eventArgs);
                                  }}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__koaEg
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__qOmK
                                      )}
                                    >
                                      {
                                        "\u062a\u063a\u06cc\u06cc\u0631 \u0648\u0636\u0639\u06cc\u062a \u0627\u0634\u062a\u0631\u0627\u06a9"
                                      }
                                    </div>
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__kkC
                                      )}
                                    >
                                      {"subscription"}
                                    </div>
                                  </div>
                                </AntdCheckbox>
                              </div>
                            </div>
                          </div>
                          <Paziresh24Button
                            children2={
                              "\u0627\u06cc\u062c\u0627\u062f \u0648\u0628\u200c\u0647\u0648\u06a9"
                            }
                            className={classNames(
                              "__wab_instance",
                              sty.paziresh24Button__o8Z3J
                            )}
                            isDisabled={(() => {
                              try {
                                return (
                                  !$state.input.value ||
                                  !$state?.subscriptionCheck.checked
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()}
                            loading={(() => {
                              try {
                                return $state.loading;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()}
                            onClick={async event => {
                              const $steps = {};

                              $steps["updateLoading"] = true
                                ? (() => {
                                    const actionArgs = {
                                      variable: {
                                        objRoot: $state,
                                        variablePath: ["loading"]
                                      },
                                      operation: 0,
                                      value: true
                                    };
                                    return (({
                                      variable,
                                      value,
                                      startIndex,
                                      deleteCount
                                    }) => {
                                      if (!variable) {
                                        return;
                                      }
                                      const { objRoot, variablePath } =
                                        variable;

                                      $stateSet(objRoot, variablePath, value);
                                      return value;
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["updateLoading"] != null &&
                                typeof $steps["updateLoading"] === "object" &&
                                typeof $steps["updateLoading"].then ===
                                  "function"
                              ) {
                                $steps["updateLoading"] =
                                  await $steps["updateLoading"];
                              }

                              $steps["invokeGlobalAction"] = true
                                ? (() => {
                                    const actionArgs = {
                                      args: [
                                        "POST",
                                        (() => {
                                          try {
                                            return `https://apigw.paziresh24.com/v1/hamdast/apps/${$state.authProvider?.apps?.find(item => item.id === $ctx.params?.id).key}/webhooks/`;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })(),
                                        undefined,
                                        (() => {
                                          try {
                                            return {
                                              url: $state.input.value,
                                              filter_types: [
                                                $state.subscriptionCheck
                                                  ?.checked
                                                  ? "subscription"
                                                  : false
                                              ].filter(Boolean)
                                            };
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                      ]
                                    };
                                    return $globalActions[
                                      "Fragment.apiRequest"
                                    ]?.apply(null, [...actionArgs.args]);
                                  })()
                                : undefined;
                              if (
                                $steps["invokeGlobalAction"] != null &&
                                typeof $steps["invokeGlobalAction"] ===
                                  "object" &&
                                typeof $steps["invokeGlobalAction"].then ===
                                  "function"
                              ) {
                                $steps["invokeGlobalAction"] =
                                  await $steps["invokeGlobalAction"];
                              }

                              $steps["updateLoading2"] = true
                                ? (() => {
                                    const actionArgs = {
                                      variable: {
                                        objRoot: $state,
                                        variablePath: ["loading"]
                                      },
                                      operation: 0,
                                      value: false
                                    };
                                    return (({
                                      variable,
                                      value,
                                      startIndex,
                                      deleteCount
                                    }) => {
                                      if (!variable) {
                                        return;
                                      }
                                      const { objRoot, variablePath } =
                                        variable;

                                      $stateSet(objRoot, variablePath, value);
                                      return value;
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["updateLoading2"] != null &&
                                typeof $steps["updateLoading2"] === "object" &&
                                typeof $steps["updateLoading2"].then ===
                                  "function"
                              ) {
                                $steps["updateLoading2"] =
                                  await $steps["updateLoading2"];
                              }

                              $steps["updateDialogOpen"] = true
                                ? (() => {
                                    const actionArgs = {
                                      variable: {
                                        objRoot: $state,
                                        variablePath: ["dialog", "open"]
                                      },
                                      operation: 0,
                                      value: false
                                    };
                                    return (({
                                      variable,
                                      value,
                                      startIndex,
                                      deleteCount
                                    }) => {
                                      if (!variable) {
                                        return;
                                      }
                                      const { objRoot, variablePath } =
                                        variable;

                                      $stateSet(objRoot, variablePath, value);
                                      return value;
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["updateDialogOpen"] != null &&
                                typeof $steps["updateDialogOpen"] ===
                                  "object" &&
                                typeof $steps["updateDialogOpen"].then ===
                                  "function"
                              ) {
                                $steps["updateDialogOpen"] =
                                  await $steps["updateDialogOpen"];
                              }

                              $steps["updateDialogOpen2"] = true
                                ? (() => {
                                    const actionArgs = {
                                      tplRef: "apiRequest",
                                      action: "refresh"
                                    };
                                    return (({ tplRef, action, args }) => {
                                      return $refs?.[tplRef]?.[action]?.(
                                        ...(args ?? [])
                                      );
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["updateDialogOpen2"] != null &&
                                typeof $steps["updateDialogOpen2"] ===
                                  "object" &&
                                typeof $steps["updateDialogOpen2"].then ===
                                  "function"
                              ) {
                                $steps["updateDialogOpen2"] =
                                  await $steps["updateDialogOpen2"];
                              }
                            }}
                            shape={"sharp"}
                          />
                        </div>
                      }
                      className={classNames("__wab_instance", sty.dialog)}
                      onOpenChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "dialog",
                          "open"
                        ]).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }
                      }}
                      open={generateStateValueProp($state, ["dialog", "open"])}
                      title={
                        "\u0648\u0628\u200c\u0647\u0648\u06a9 \u062c\u062f\u06cc\u062f"
                      }
                      trigger={
                        <Paziresh24Button
                          children2={
                            "\u0627\u06cc\u062c\u0627\u062f \u0648\u0628 \u0647\u0648\u06a9"
                          }
                          className={classNames(
                            "__wab_instance",
                            sty.paziresh24Button__iw0Sh
                          )}
                          shape={"sharp"}
                          showStartIcon={true}
                          size={"compact"}
                          startIcon={
                            <Icon21Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xqNvc
                              )}
                              role={"img"}
                            />
                          }
                        />
                      }
                    />
                  </div>
                </div>
                <ApiRequest
                  data-plasmic-name={"apiRequest"}
                  data-plasmic-override={overrides.apiRequest}
                  className={classNames("__wab_instance", sty.apiRequest)}
                  errorDisplay={null}
                  loadingDisplay={
                    <Icon15Icon
                      className={classNames(projectcss.all, sty.svg__kckiM)}
                      role={"img"}
                    />
                  }
                  method={"GET"}
                  onError={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "apiRequest",
                      "error"
                    ]).apply(null, eventArgs);
                  }}
                  onLoading={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "apiRequest",
                      "loading"
                    ]).apply(null, eventArgs);
                  }}
                  onSuccess={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "apiRequest",
                      "data"
                    ]).apply(null, eventArgs);
                  }}
                  ref={ref => {
                    $refs["apiRequest"] = ref;
                  }}
                  url={(() => {
                    try {
                      return `https://apigw.paziresh24.com/v1/hamdast/apps/${$state.authProvider?.apps?.find(item => item.id === $ctx.params?.id).key}/webhooks/`;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  {(() => {
                    try {
                      return $state.apiRequest?.data?.data?.length === 0;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Y5Sa
                      )}
                    >
                      {
                        "\u0648\u0628\u200c\u0647\u0648\u06a9\u06cc \u0648\u062c\u0648\u062f \u0646\u062f\u0627\u0631\u062f."
                      }
                    </div>
                  ) : null}
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $state.apiRequest.data.data;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <WebhookCard
                        data-plasmic-name={"webhookCard"}
                        data-plasmic-override={overrides.webhookCard}
                        appKey={(() => {
                          try {
                            return $state.authProvider?.apps?.find(
                              item => item.id === $ctx.params?.id
                            ).key;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        className={classNames(
                          "__wab_instance",
                          sty.webhookCard
                        )}
                        currentItem={(() => {
                          try {
                            return currentItem;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        key={currentIndex}
                        refresh={async () => {
                          const $steps = {};

                          $steps["runActionOnApiRequest"] = true
                            ? (() => {
                                const actionArgs = {
                                  tplRef: "apiRequest",
                                  action: "refresh"
                                };
                                return (({ tplRef, action, args }) => {
                                  return $refs?.[tplRef]?.[action]?.(
                                    ...(args ?? [])
                                  );
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["runActionOnApiRequest"] != null &&
                            typeof $steps["runActionOnApiRequest"] ===
                              "object" &&
                            typeof $steps["runActionOnApiRequest"].then ===
                              "function"
                          ) {
                            $steps["runActionOnApiRequest"] =
                              await $steps["runActionOnApiRequest"];
                          }
                        }}
                      />
                    );
                  })}
                </ApiRequest>
              </div>
            </Layout>
          </AuthProvider>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "embedHtml",
    "authProvider",
    "layout",
    "dialog",
    "input",
    "subscriptionCheck",
    "apiRequest",
    "webhookCard"
  ],
  embedHtml: ["embedHtml"],
  authProvider: [
    "authProvider",
    "layout",
    "dialog",
    "input",
    "subscriptionCheck",
    "apiRequest",
    "webhookCard"
  ],
  layout: [
    "layout",
    "dialog",
    "input",
    "subscriptionCheck",
    "apiRequest",
    "webhookCard"
  ],
  dialog: ["dialog", "input", "subscriptionCheck"],
  input: ["input"],
  subscriptionCheck: ["subscriptionCheck"],
  apiRequest: ["apiRequest", "webhookCard"],
  webhookCard: ["webhookCard"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  embedHtml: typeof Embed;
  authProvider: typeof AuthProvider;
  layout: typeof Layout;
  dialog: typeof Paziresh24Modal;
  input: typeof Input;
  subscriptionCheck: typeof AntdCheckbox;
  apiRequest: typeof ApiRequest;
  webhookCard: typeof WebhookCard;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWebhooks__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWebhooks__VariantsArgs;
    args?: PlasmicWebhooks__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWebhooks__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWebhooks__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWebhooks__ArgProps,
          internalVariantPropNames: PlasmicWebhooks__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWebhooks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWebhooks";
  } else {
    func.displayName = `PlasmicWebhooks.${nodeName}`;
  }
  return func;
}

export const PlasmicWebhooks = Object.assign(
  // Top-level PlasmicWebhooks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    embedHtml: makeNodeComponent("embedHtml"),
    authProvider: makeNodeComponent("authProvider"),
    layout: makeNodeComponent("layout"),
    dialog: makeNodeComponent("dialog"),
    input: makeNodeComponent("input"),
    subscriptionCheck: makeNodeComponent("subscriptionCheck"),
    apiRequest: makeNodeComponent("apiRequest"),
    webhookCard: makeNodeComponent("webhookCard"),

    // Metadata about props expected for PlasmicWebhooks
    internalVariantProps: PlasmicWebhooks__VariantProps,
    internalArgProps: PlasmicWebhooks__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "وب هوک",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicWebhooks;
/* prettier-ignore-end */
