/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bE9NMB942w5e6uFrcCxfJN
// Component: OpfjC8Ncgqxa

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Paziresh24LineClamp from "../../Paziresh24LineClamp"; // plasmic-import: xFfrwlkCaWS8/component
import Paziresh24Button from "../../Paziresh24Button"; // plasmic-import: YOhw5fIQJQgB/component
import Paziresh24Modal from "../../Paziresh24Modal"; // plasmic-import: ZGdhyEBPJSmH/component
import { Input } from "@/fragment/components/input"; // plasmic-import: AWE69UKwmIyg/codeComponent
import { AntdCheckbox } from "@plasmicpkgs/antd5/skinny/registerCheckbox";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectcss
import sty from "./PlasmicWebhookCard.module.css"; // plasmic-import: OpfjC8Ncgqxa/css

import IconIcon from "../ravi_design_system/icons/PlasmicIcon__Icon"; // plasmic-import: 2uzLLHig1Vpp/icon
import ChevronLeftIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: jS0YlkKPLO7U/icon
import ChevronRightIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronRight"; // plasmic-import: 0359howWu0cr/icon

createPlasmicElementProxy;

export type PlasmicWebhookCard__VariantMembers = {};
export type PlasmicWebhookCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicWebhookCard__VariantsArgs;
export const PlasmicWebhookCard__VariantProps = new Array<VariantPropType>();

export type PlasmicWebhookCard__ArgsType = {
  currentItem?: any;
  refresh?: () => void;
  appKey?: string;
};
type ArgPropType = keyof PlasmicWebhookCard__ArgsType;
export const PlasmicWebhookCard__ArgProps = new Array<ArgPropType>(
  "currentItem",
  "refresh",
  "appKey"
);

export type PlasmicWebhookCard__OverridesType = {
  root?: Flex__<"div">;
  paziresh24LineClamp?: Flex__<typeof Paziresh24LineClamp>;
  svg?: Flex__<"svg">;
  dialog?: Flex__<typeof Paziresh24Modal>;
  input?: Flex__<typeof Input>;
  subscriptionCheck?: Flex__<typeof AntdCheckbox>;
};

export interface DefaultWebhookCardProps {
  currentItem?: any;
  refresh?: () => void;
  appKey?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWebhookCard__RenderFunc(props: {
  variants: PlasmicWebhookCard__VariantsArgs;
  args: PlasmicWebhookCard__ArgsType;
  overrides: PlasmicWebhookCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "dialog.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.currentItem.url;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "subscriptionCheck.checked",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.currentItem.filterTypes?.includes("subscription");
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___9PSLc)}>
        <div className={classNames(projectcss.all, sty.freeBox__neucz)}>
          <Paziresh24LineClamp
            data-plasmic-name={"paziresh24LineClamp"}
            data-plasmic-override={overrides.paziresh24LineClamp}
            className={classNames("__wab_instance", sty.paziresh24LineClamp)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mgJue
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.currentItem.url;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </Paziresh24LineClamp>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__tFrQp)}>
          <Paziresh24Button
            children2={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dfJu
                )}
              >
                {"\u0648\u06cc\u0631\u0627\u06cc\u0634"}
              </div>
            }
            className={classNames(
              "__wab_instance",
              sty.paziresh24Button__bRMiA
            )}
            onClick={async event => {
              const $steps = {};

              $steps["updateDialogOpen"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["dialog", "open"]
                      },
                      operation: 0,
                      value: true
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateDialogOpen"] != null &&
                typeof $steps["updateDialogOpen"] === "object" &&
                typeof $steps["updateDialogOpen"].then === "function"
              ) {
                $steps["updateDialogOpen"] = await $steps["updateDialogOpen"];
              }
            }}
            outline={true}
            shape={"sharp"}
            showStartIcon={true}
            size={"compact"}
            startIcon={
              <IconIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
          />

          <Paziresh24Modal
            data-plasmic-name={"dialog"}
            data-plasmic-override={overrides.dialog}
            body={
              <div className={classNames(projectcss.all, sty.freeBox__rfCHp)}>
                <div className={classNames(projectcss.all, sty.freeBox__uiGxN)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__clPkZ
                    )}
                  >
                    {
                      "\u0622\u062f\u0631\u0633 \u0648\u0628\u200c\u0647\u0648\u06a9"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gxz2U
                    )}
                  >
                    {
                      "\u0645\u0627 \u06cc\u06a9 \u062f\u0631\u062e\u0648\u0627\u0633\u062a POST \u0628\u0647 \u0647\u0645\u0631\u0627\u0647 \u062c\u0632\u0626\u06cc\u0627\u062a \u0647\u0631 \u0631\u0648\u06cc\u062f\u0627\u062f \u0628\u0647 URL \u0632\u06cc\u0631 \u0627\u0631\u0633\u0627\u0644 \u062e\u0648\u0627\u0647\u06cc\u0645 \u06a9\u0631\u062f.\r"
                    }
                  </div>
                  <Input
                    data-plasmic-name={"input"}
                    data-plasmic-override={overrides.input}
                    attributes={{ dir: "ltr" }}
                    className={classNames("__wab_instance", sty.input)}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "input",
                        "value"
                      ]).apply(null, eventArgs);
                    }}
                    placeholder={"https://example.com/postreceive"}
                    type={"text"}
                    value={generateStateValueProp($state, ["input", "value"])}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zVxsy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dc0Ll
                    )}
                  >
                    {"\u0631\u0648\u06cc\u062f\u0627\u062f"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rKfyZ
                    )}
                  >
                    {
                      "\u0686\u0647 \u0646\u0648\u0639 \u0631\u0648\u06cc\u062f\u0627\u062f \u0647\u0627\u06cc\u06cc \u0628\u0647 \u0627\u0628\u0632\u0627\u0631\u06a9 \u0627\u0637\u0644\u0627\u0639\u200c\u0631\u0633\u0627\u0646\u06cc \u0634\u0648\u062f\u061f"
                    }
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__p2T56)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ajY9U)}
                    >
                      <AntdCheckbox
                        data-plasmic-name={"subscriptionCheck"}
                        data-plasmic-override={overrides.subscriptionCheck}
                        checked={generateStateValueProp($state, [
                          "subscriptionCheck",
                          "checked"
                        ])}
                        className={classNames(
                          "__wab_instance",
                          sty.subscriptionCheck
                        )}
                        defaultChecked={(() => {
                          try {
                            return $props.currentItem.filterTypes?.includes(
                              "subscription"
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        indeterminate={false}
                        onChange={async (...eventArgs: any) => {
                          generateStateOnChangeProp($state, [
                            "subscriptionCheck",
                            "checked"
                          ]).apply(null, eventArgs);
                        }}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__a7HhW
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zgf1I
                            )}
                          >
                            {
                              "\u062a\u063a\u06cc\u06cc\u0631 \u0648\u0636\u0639\u06cc\u062a \u0627\u0634\u062a\u0631\u0627\u06a9"
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qwbaD
                            )}
                          >
                            {"subscription"}
                          </div>
                        </div>
                      </AntdCheckbox>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kzfy)}>
                  <Paziresh24Button
                    children2={
                      "\u0648\u06cc\u0631\u0627\u06cc\u0634 \u0648\u0628\u200c\u0647\u0648\u06a9"
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.paziresh24Button__xVjXf
                    )}
                    isDisabled={(() => {
                      try {
                        return (
                          !$state.input.value ||
                          !$state?.subscriptionCheck.checked
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()}
                    loading={(() => {
                      try {
                        return $state.loading;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateLoading"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["loading"]
                              },
                              operation: 0,
                              value: true
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading"] != null &&
                        typeof $steps["updateLoading"] === "object" &&
                        typeof $steps["updateLoading"].then === "function"
                      ) {
                        $steps["updateLoading"] = await $steps["updateLoading"];
                      }

                      $steps["invokeGlobalAction"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                "PATCH",
                                (() => {
                                  try {
                                    return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/webhooks/${$props.currentItem.id}`;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                undefined,
                                (() => {
                                  try {
                                    return {
                                      url: $state.input.value,
                                      filter_types: [
                                        $state.subscriptionCheck?.checked
                                          ? "subscription"
                                          : false
                                      ].filter(Boolean)
                                    };
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()
                              ]
                            };
                            return $globalActions["Fragment.apiRequest"]?.apply(
                              null,
                              [...actionArgs.args]
                            );
                          })()
                        : undefined;
                      if (
                        $steps["invokeGlobalAction"] != null &&
                        typeof $steps["invokeGlobalAction"] === "object" &&
                        typeof $steps["invokeGlobalAction"].then === "function"
                      ) {
                        $steps["invokeGlobalAction"] =
                          await $steps["invokeGlobalAction"];
                      }

                      $steps["updateLoading2"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["loading"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading2"] != null &&
                        typeof $steps["updateLoading2"] === "object" &&
                        typeof $steps["updateLoading2"].then === "function"
                      ) {
                        $steps["updateLoading2"] =
                          await $steps["updateLoading2"];
                      }

                      $steps["updateLoading3"] = true
                        ? (() => {
                            const actionArgs = { eventRef: $props["refresh"] };
                            return (({ eventRef, args }) => {
                              return eventRef?.(...(args ?? []));
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading3"] != null &&
                        typeof $steps["updateLoading3"] === "object" &&
                        typeof $steps["updateLoading3"].then === "function"
                      ) {
                        $steps["updateLoading3"] =
                          await $steps["updateLoading3"];
                      }

                      $steps["updateLoading4"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dialog", "open"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading4"] != null &&
                        typeof $steps["updateLoading4"] === "object" &&
                        typeof $steps["updateLoading4"].then === "function"
                      ) {
                        $steps["updateLoading4"] =
                          await $steps["updateLoading4"];
                      }
                    }}
                    shape={"sharp"}
                  />

                  <Paziresh24Button
                    children2={"\u062d\u0630\u0641"}
                    className={classNames(
                      "__wab_instance",
                      sty.paziresh24Button__sbMin
                    )}
                    color={"red"}
                    loading={(() => {
                      try {
                        return $state.loading;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateLoading"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["loading"]
                              },
                              operation: 0,
                              value: true
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading"] != null &&
                        typeof $steps["updateLoading"] === "object" &&
                        typeof $steps["updateLoading"].then === "function"
                      ) {
                        $steps["updateLoading"] = await $steps["updateLoading"];
                      }

                      $steps["invokeGlobalAction"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                "DELETE",
                                (() => {
                                  try {
                                    return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/webhooks/${$props.currentItem.id}`;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()
                              ]
                            };
                            return $globalActions["Fragment.apiRequest"]?.apply(
                              null,
                              [...actionArgs.args]
                            );
                          })()
                        : undefined;
                      if (
                        $steps["invokeGlobalAction"] != null &&
                        typeof $steps["invokeGlobalAction"] === "object" &&
                        typeof $steps["invokeGlobalAction"].then === "function"
                      ) {
                        $steps["invokeGlobalAction"] =
                          await $steps["invokeGlobalAction"];
                      }

                      $steps["updateLoading2"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["loading"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading2"] != null &&
                        typeof $steps["updateLoading2"] === "object" &&
                        typeof $steps["updateLoading2"].then === "function"
                      ) {
                        $steps["updateLoading2"] =
                          await $steps["updateLoading2"];
                      }

                      $steps["updateLoading4"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dialog", "open"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading4"] != null &&
                        typeof $steps["updateLoading4"] === "object" &&
                        typeof $steps["updateLoading4"].then === "function"
                      ) {
                        $steps["updateLoading4"] =
                          await $steps["updateLoading4"];
                      }

                      $steps["updateLoading3"] = true
                        ? (() => {
                            const actionArgs = { eventRef: $props["refresh"] };
                            return (({ eventRef, args }) => {
                              return eventRef?.(...(args ?? []));
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLoading3"] != null &&
                        typeof $steps["updateLoading3"] === "object" &&
                        typeof $steps["updateLoading3"].then === "function"
                      ) {
                        $steps["updateLoading3"] =
                          await $steps["updateLoading3"];
                      }
                    }}
                    outline={true}
                    shape={"sharp"}
                  />
                </div>
              </div>
            }
            className={classNames("__wab_instance", sty.dialog)}
            noTrigger={true}
            onOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["dialog", "open"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            open={generateStateValueProp($state, ["dialog", "open"])}
            title={
              "\u0648\u06cc\u0631\u0627\u06cc\u0634 \u0648\u0628\u200c\u0647\u0648\u06a9"
            }
            trigger={null}
          />
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__rq16)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__yxfHy
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return (
                  "تاریخ ایجاد: " +
                  new Date($props.currentItem.createdAt).toLocaleDateString(
                    "fa"
                  )
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___2HC5W)}>
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $props.currentItem.filterTypes;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__e6Lqs
                )}
                key={currentIndex}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return currentItem;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "paziresh24LineClamp",
    "svg",
    "dialog",
    "input",
    "subscriptionCheck"
  ],
  paziresh24LineClamp: ["paziresh24LineClamp"],
  svg: ["svg"],
  dialog: ["dialog", "input", "subscriptionCheck"],
  input: ["input"],
  subscriptionCheck: ["subscriptionCheck"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  paziresh24LineClamp: typeof Paziresh24LineClamp;
  svg: "svg";
  dialog: typeof Paziresh24Modal;
  input: typeof Input;
  subscriptionCheck: typeof AntdCheckbox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWebhookCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWebhookCard__VariantsArgs;
    args?: PlasmicWebhookCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWebhookCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWebhookCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWebhookCard__ArgProps,
          internalVariantPropNames: PlasmicWebhookCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWebhookCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWebhookCard";
  } else {
    func.displayName = `PlasmicWebhookCard.${nodeName}`;
  }
  return func;
}

export const PlasmicWebhookCard = Object.assign(
  // Top-level PlasmicWebhookCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    paziresh24LineClamp: makeNodeComponent("paziresh24LineClamp"),
    svg: makeNodeComponent("svg"),
    dialog: makeNodeComponent("dialog"),
    input: makeNodeComponent("input"),
    subscriptionCheck: makeNodeComponent("subscriptionCheck"),

    // Metadata about props expected for PlasmicWebhookCard
    internalVariantProps: PlasmicWebhookCard__VariantProps,
    internalArgProps: PlasmicWebhookCard__ArgProps
  }
);

export default PlasmicWebhookCard;
/* prettier-ignore-end */
