/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bE9NMB942w5e6uFrcCxfJN
// Component: ZHuPkRDeQgyK

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Paziresh24LineClamp from "../../Paziresh24LineClamp"; // plasmic-import: xFfrwlkCaWS8/component
import Paziresh24Modal from "../../Paziresh24Modal"; // plasmic-import: ZGdhyEBPJSmH/component
import Paziresh24Button from "../../Paziresh24Button"; // plasmic-import: YOhw5fIQJQgB/component
import PlanForm from "../../PlanForm"; // plasmic-import: f7fOrAClVFZA/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bE9NMB942w5e6uFrcCxfJN/projectcss
import sty from "./PlasmicPlanCard.module.css"; // plasmic-import: ZHuPkRDeQgyK/css

import Icon24Icon from "./icons/PlasmicIcon__Icon24"; // plasmic-import: 3P4kCztjZFA7/icon
import IconIcon from "../ravi_design_system/icons/PlasmicIcon__Icon"; // plasmic-import: 2uzLLHig1Vpp/icon
import ChevronLeftIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: jS0YlkKPLO7U/icon

import __lib_copyToClipboard from "copy-to-clipboard";

createPlasmicElementProxy;

export type PlasmicPlanCard__VariantMembers = {};
export type PlasmicPlanCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicPlanCard__VariantsArgs;
export const PlasmicPlanCard__VariantProps = new Array<VariantPropType>();

export type PlasmicPlanCard__ArgsType = {
  currentItem?: any;
  refresh?: () => void;
  appKey?: string;
};
type ArgPropType = keyof PlasmicPlanCard__ArgsType;
export const PlasmicPlanCard__ArgProps = new Array<ArgPropType>(
  "currentItem",
  "refresh",
  "appKey"
);

export type PlasmicPlanCard__OverridesType = {
  root?: Flex__<"div">;
  paziresh24LineClamp?: Flex__<typeof Paziresh24LineClamp>;
  dialog?: Flex__<typeof Paziresh24Modal>;
  paziresh24Button?: Flex__<typeof Paziresh24Button>;
  planForm?: Flex__<typeof PlanForm>;
};

export interface DefaultPlanCardProps {
  currentItem?: any;
  refresh?: () => void;
  appKey?: string;
  className?: string;
}

const $$ = {
  copyToClipboard: __lib_copyToClipboard
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPlanCard__RenderFunc(props: {
  variants: PlasmicPlanCard__VariantsArgs;
  args: PlasmicPlanCard__ArgsType;
  overrides: PlasmicPlanCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dialog.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__vMp3K)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__uPr4G
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.currentItem.title;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___2Rw5X)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mfn0S
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return {
                  weekly: "هفتگی",
                  monthly: "ماهانه",
                  quarterly: "سه‌ماهه",
                  semiannual: "شش‌ماهه",
                  yearly: "سالانه"
                }[$props.currentItem.interval];
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__xYjAo)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kKPil
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return ($props.currentItem.amount / 10).toLocaleString("fa-ir");
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__l586B)}
        onClick={async event => {
          const $steps = {};

          $steps["runCode"] = true
            ? (() => {
                const actionArgs = {
                  customFunction: async () => {
                    return $$.copyToClipboard($props.currentItem.id);
                  }
                };
                return (({ customFunction }) => {
                  return customFunction();
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["runCode"] != null &&
            typeof $steps["runCode"] === "object" &&
            typeof $steps["runCode"].then === "function"
          ) {
            $steps["runCode"] = await $steps["runCode"];
          }

          $steps["invokeGlobalAction"] = true
            ? (() => {
                const actionArgs = {
                  args: [
                    undefined,
                    "\u06a9\u067e\u06cc \u0634\u062f.",
                    "top-center"
                  ]
                };
                return $globalActions["Fragment.showToast"]?.apply(null, [
                  ...actionArgs.args
                ]);
              })()
            : undefined;
          if (
            $steps["invokeGlobalAction"] != null &&
            typeof $steps["invokeGlobalAction"] === "object" &&
            typeof $steps["invokeGlobalAction"].then === "function"
          ) {
            $steps["invokeGlobalAction"] = await $steps["invokeGlobalAction"];
          }
        }}
      >
        <Paziresh24LineClamp
          data-plasmic-name={"paziresh24LineClamp"}
          data-plasmic-override={overrides.paziresh24LineClamp}
          className={classNames("__wab_instance", sty.paziresh24LineClamp)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yRe7
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.currentItem.id;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </Paziresh24LineClamp>
        <Icon24Icon
          className={classNames(projectcss.all, sty.svg__xSmcz)}
          role={"img"}
        />
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___00Rjk)}>
        <Paziresh24Modal
          data-plasmic-name={"dialog"}
          data-plasmic-override={overrides.dialog}
          body={
            <PlanForm
              data-plasmic-name={"planForm"}
              data-plasmic-override={overrides.planForm}
              appKey={(() => {
                try {
                  return $props.appKey;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              className={classNames("__wab_instance", sty.planForm)}
              defaultValue={(() => {
                try {
                  return $props.currentItem;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              onSubmit={async () => {
                const $steps = {};

                $steps["updateDialogOpen"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["dialog", "open"]
                        },
                        operation: 0,
                        value: false
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateDialogOpen"] != null &&
                  typeof $steps["updateDialogOpen"] === "object" &&
                  typeof $steps["updateDialogOpen"].then === "function"
                ) {
                  $steps["updateDialogOpen"] = await $steps["updateDialogOpen"];
                }

                $steps["updateDialogOpen2"] = true
                  ? (() => {
                      const actionArgs = { eventRef: $props["refresh"] };
                      return (({ eventRef, args }) => {
                        return eventRef?.(...(args ?? []));
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateDialogOpen2"] != null &&
                  typeof $steps["updateDialogOpen2"] === "object" &&
                  typeof $steps["updateDialogOpen2"].then === "function"
                ) {
                  $steps["updateDialogOpen2"] =
                    await $steps["updateDialogOpen2"];
                }
              }}
              planId={(() => {
                try {
                  return $props.currentItem.id;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              submitButtonText={
                "\u0648\u06cc\u0631\u0627\u06cc\u0634 \u067e\u0644\u0646"
              }
            />
          }
          className={classNames("__wab_instance", sty.dialog)}
          onOpenChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["dialog", "open"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          open={generateStateValueProp($state, ["dialog", "open"])}
          title={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vVUts
              )}
            >
              {"\u0648\u06cc\u0631\u0627\u06cc\u0634 \u067e\u0644\u0646"}
            </div>
          }
          trigger={
            <Paziresh24Button
              data-plasmic-name={"paziresh24Button"}
              data-plasmic-override={overrides.paziresh24Button}
              children2={"\u0648\u06cc\u0631\u0627\u06cc\u0634"}
              className={classNames("__wab_instance", sty.paziresh24Button)}
              outline={true}
              shape={"sharp"}
              showStartIcon={true}
              size={"compact"}
              startIcon={
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__ocyak)}
                  role={"img"}
                />
              }
            />
          }
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "paziresh24LineClamp",
    "dialog",
    "paziresh24Button",
    "planForm"
  ],
  paziresh24LineClamp: ["paziresh24LineClamp"],
  dialog: ["dialog", "paziresh24Button", "planForm"],
  paziresh24Button: ["paziresh24Button"],
  planForm: ["planForm"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  paziresh24LineClamp: typeof Paziresh24LineClamp;
  dialog: typeof Paziresh24Modal;
  paziresh24Button: typeof Paziresh24Button;
  planForm: typeof PlanForm;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPlanCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPlanCard__VariantsArgs;
    args?: PlasmicPlanCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPlanCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPlanCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPlanCard__ArgProps,
          internalVariantPropNames: PlasmicPlanCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPlanCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPlanCard";
  } else {
    func.displayName = `PlasmicPlanCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPlanCard = Object.assign(
  // Top-level PlasmicPlanCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    paziresh24LineClamp: makeNodeComponent("paziresh24LineClamp"),
    dialog: makeNodeComponent("dialog"),
    paziresh24Button: makeNodeComponent("paziresh24Button"),
    planForm: makeNodeComponent("planForm"),

    // Metadata about props expected for PlasmicPlanCard
    internalVariantProps: PlasmicPlanCard__VariantProps,
    internalArgProps: PlasmicPlanCard__ArgProps
  }
);

export default PlasmicPlanCard;
/* prettier-ignore-end */
